//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasicCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnswerArchive
    {
        public Nullable<int> AnswerId { get; set; }
        public Nullable<int> TestsArchiveId { get; set; }
        public Nullable<bool> IsChecked { get; set; }
        public int AnswerArchiveId { get; set; }
    
        public virtual Answer Answer { get; set; }
        public virtual TestsArchive TestsArchive { get; set; }
    }
}
