//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasicCRM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BasicCRMEntities : DbContext
    {
        public BasicCRMEntities()
            : base("name=BasicCRMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Answer> Answers { get; set; }
        public virtual DbSet<Bunch> Bunches { get; set; }
        public virtual DbSet<Lesson> Lessons { get; set; }
        public virtual DbSet<Level> Levels { get; set; }
        public virtual DbSet<LevelType> LevelTypes { get; set; }
        public virtual DbSet<Passport> Passports { get; set; }
        public virtual DbSet<PassportType> PassportTypes { get; set; }
        public virtual DbSet<PhoneNumber> PhoneNumbers { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<Test> Tests { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UsersStatus> UsersStatuses { get; set; }
        public virtual DbSet<Weekday> Weekdays { get; set; }
    }
}
