//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasicCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bunch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bunch()
        {
            this.Weekdays = new HashSet<Weekday>();
        }
    
        public int BunchID { get; set; }
        public string BunchName { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> LevelID { get; set; }
        public Nullable<System.DateTime> RegistationDate { get; set; }
        public Nullable<System.DateTime> CompleteDate { get; set; }
        public Nullable<int> RoomID { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
    
        public virtual Level Level { get; set; }
        public virtual Room Room { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Weekday> Weekdays { get; set; }
    }
}
