//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasicCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passport
    {
        public int PassportID { get; set; }
        public string Number { get; set; }
        public string Authorithy { get; set; }
        public Nullable<System.DateTime> DateOfIssue { get; set; }
        public Nullable<int> PassportTypeID { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual PassportType PassportType { get; set; }
        public virtual User User { get; set; }
    }
}
