//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasicCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestsArchive
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TestsArchive()
        {
            this.AnswerArchives = new HashSet<AnswerArchive>();
        }
    
        public int TestsArchiveId { get; set; }
        public Nullable<int> TestId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
        public Nullable<decimal> UserScore { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnswerArchive> AnswerArchives { get; set; }
        public virtual Test Test { get; set; }
        public virtual User User { get; set; }
    }
}
